config/routes.rb
Rails.application.routes.draw do

  # get '/groups/new', to: 'groups#new', as: 'new_group'
  # get '/groups/:id', to: 'groups#show', as: 'group'
  
  root to: 'users#index'

  get '/auth/github/callback' => 'sessions#create'

  get '/signup', to: 'users#new', as: 'users'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  # post '/users/:user_id/groups', to: 'groups#create', as: 'user_groups'

  get '/users/most_tasks', to: 'users#most_tasks', as: 'most_tasks'


  # get '/groups/:id/group_tasks', to: 'group_tasks#new', as: 'new_group_group_task'
  # post '/groups/:id/group_tasks', to: 'group_tasks#create', as: 'group_tasks'
  # patch '/group_tasks/:id/edit', to: 'group_tasks#update', as: 'group_group_task'
  # get '/groups/:id/new', to: 'group_tasks#new', as: 'new_group_task'
  # patch '/groups/:group_id/goal', to: 'goals#create', as: 'group_goal'
  # #group goals
  # get '/groups/:id/goal', to: 'goals#new', as: 'group_goals'
  # post '/goals', to: 'goals#create'
  # get '/groups/:id/goal/:id/edit', to: 'goals#edit', as: 'edit_group_goal'
  # patch 'groups/:id/goals/:id', to: 'goals#update'

  # #user goals
  # get '/users/:id/goal', to: 'goals#new', as: 'user_goals'
  # post '/users/:id/goal', to: 'goals#create'
  # get '/users/:user_id/goal/:id/edit', to: 'goals#edit', as: 'edit_user_goal'
  patch '/goals/:id', to: 'goals#update'
  post '/goals', to: 'goals#create'

  # post '/users/:id/tasks', to: 'tasks#create'
  # delete '/task/:id', to: 'tasks#destroy', as: 'task'
# patch '/users/:user_id/tasks/:id', to: 'tasks#update'
# get '/users/:user_id/tasks/:id/edit', to: 'tasks#edit', as: 'edit_user_tasks'

  # delete 'groups/:group_id/task/:id', to: 'group_tasks#destroy', as: 'group_task'

  #Comments
  get '/users/:user_id/tasks/:id/comment', to: 'tasks#edit', as: 'comment_user_tasks'
  patch '/users/:user_id/tasks/:id/comment', to: 'tasks#update', as: 'update_comment_user_tasks'
  
  
  get '/groups/:group_id/tasks/:id/comment', to: 'group_tasks#edit', as: 'comment_group_task'
  patch '/groups/:group_id/tasks/:id/comment', to: 'group_tasks#update', as: 'update_comment_group_task'

  
 
  
  

  
  get '/users/:user_id/groups/:id/edit', to: 'groups#edit', as: 'edit_user_group'
  get '/users/:user_id/tasks/:id/goal/:status', to: 'tasks#edit', as: 'goal_user_task'
  get 'groups/:group_id/tasks/:id/:complete', to: 'group_tasks#edit', as: 'complete_group_task'
  get 'users/:user_id/tasks/:id/:complete', to: 'tasks#edit', as: 'complete_user_task'
  

  resources :users, only: [:show, :edit, :update] do
    # resources :tasks, only: [:new, :create, :edit, :update]
    resources :tasks, only: [:new, :create, :edit, :update, :destroy]
    resources :goals, only: [:new, :create, :show, :edit, :update]
  end

  resources :groups do
    resources :group_tasks, only: [:new, :create, :update, :destroy]
    resources :goals, only: [:new, :create, :edit, :update]
  end
  

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_tasks
  has_many :group_users
  has_many :categories, through: :group_tasks
  has_many :users, through: :group_users
  has_many :tasks
  has_one :goal
  validates_presence_of :name
  validates_uniqueness_of :name
  
  
  
  # def my_link_to(text, href)
  #   if !group_member
  #   flash[:message] = "Must be a part of group to view page" if self.users.include?(current_user)
  #   redirect_to request.referrer
  #   else 
  #     "<a href='#{href}'>#{text}</a>".html_safe
  #   end
  # end



  def group_member?
    self.users.include?(@user)
  end

  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:index]
  

  def index
    @user = current_user
    @groups = Group.all
  end
  
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)   
    @group.users << current_user
    
    if @group.save
      flash[:message] = "#{@group.name} has been created!"
      render :show
    else
      render :new
    end
  end

  def show
    if @group = Group.find_by_id(params[:id])
    
      if @group.users.include?(current_user)
    
      else
        flash[:message] = "You are not a member of that group"
        redirect_to action: "index"
      end
    
    else
      flash[:message] = "That Group doesn't exist."
      redirect_to action: "index"
    end
  end

  def edit
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
        @group = Group.find_by_id(params[:id])
        @user.groups.delete(@group)
    else
        flash[:message] = "That user doesn't exist"
    end
  end

  def update
    @group = Group.find_by_id(params[:id])
    if current_user.groups.include?(@group)
                current_user.groups.delete(@group)
    else
      @group.users << current_user
    end
    redirect_to group_path(@group)
  end

  def destroy
    if @group = Group.find_by_id(params[:id])
      if @group.users.include?(current_user)
        flash[:message] = "#{@group.name} has been deleted"
        @group.delete
      else
        flash[:message] = "Must be a member of #{group.name} to delete"
      end
    end
    redirect_to action: :index
  end

  private
  def group_params
    params.require(:group).permit(
      :name,
      :goal,
      :category_name,
      :id
    )
    end

end

app/helpers/groups_helper.rb
module GroupsHelper

end

app/views/groups/edit.html.erb
<%= render partial: "layouts/errors", locals: {object: @group} %>

<%= form_for ([@user, @group]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Join Group"%>
<% end %>

app/views/groups/index.html.erb
<% @groups.each do |group| %>
<div class="group-box <%= group.id %> col-xs-10 col-xs-offset-1 color-<%= (1..10).to_a.sample %>">
<p><h1>Group Name: </h1><h3>
<% if group.users.include?(current_user) %>
<%= link_to group.name, group_path(group) %></h3></p>
<% else%>
      <%= group.name %>
<% end %>
<ol>
<% group.users.uniq.each do |user| %>
<li><%= user.username %></li>
<% end%>
</ol>
      <% if group.users.include?(current_user)%>
      <%= link_to "Leave Group", group_path(group), method: :patch, :data => {:confirm => 'Are you sure?'} %>
      <%= link_to "Add a task", new_group_group_task_path(group) %></div> 
      <%= link_to "Delete Group", group_path(group), method: :delete %>
      <% else %>
      <%= link_to "Join Group", group_path(group), method: :patch %>
      <% end%>
      
<% end %>
<div>
<%= link_to "Create a Group", new_group_path %>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>
<%= render partial: "layouts/errors", locals: {object: @group} %>

<%= form_for(@group) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/groups/show.html.erb
<div><h1>Group Name: <u><%= @group.name %></u></h1><br>
<% if !@group.goal %>
     <h3>What is the group's goal?</h3>
     <%= form_with model: Goal.new, method: :post, url: group_goals_path(@group) do |f| %>
     <%= f.label :name, "Goal=" %>
     <%= f.text_field :name %>
     <%= f.hidden_field :group_id, :value => @group.id %>
     <%= f.submit "Create Goal" %>
     <% end %>
<% else %>
     <h2>Group Goal: <%= @group.goal.name  %></h2>
     <h4>Change <%= @group.name.pluralize %> Goal </h4>
     <%= form_with model: @group.goal, method: :patch, url: group_goal_path(@group, @group.goal) do |f| %>
     <%= f.label :name, "Goal=" %>
     <%= f.text_field :name %>
     <%= f.hidden_field :group_id, :value => @group.id %>
     <%= f.submit "Change Goal", :data => {:confirm => 'Are you sure?'} %>
     <% end %>
<% end%>

<% @group.categories.uniq.each do |category| %>
<div><p><h2>Categories: </h2><strong><%= category.name %></strong><br></p>
<div><h3>Tasks: </h3>
<ul>
<% @group.group_tasks.each do |task|%>
<% if task.category != category %>
<% next %>
<% end %>
<% com = task.comment.nil? ? "Add Comment" : "Update Comment" %>
<% if task.complete == true %>
          <del><p><em><li><%= task.name  %></li></em></del><em> (Task Completed!)</em><br>
               <b>Comment:</b> <em><%= task.comment %></em></p>
          <%= link_to com, comment_group_task_path(@group, task) %>
          <% else %>
           <p><em><li><%= task.name  %></li></em><br>
          <b>Comment:</b> <em><%= task.comment %></em></p>          
         <%= link_to com, comment_group_task_path(@group, task) %><br>
         <%= link_to "Completed?", complete_group_task_path(@group, task, "true") %>
        <% end%>
        <%= link_to "Delete Task", group_group_task_path(@group, task), method: 'delete' %>
        <br>
        <hr>
</div>
<% end%>
</div>
<% end %>
</ul>
<hr>
<h3>Group Members:</h3>
<ul>
<% @group.users.uniq.each do |user|%>
<li><%= user.username %><br></li>
<% end %>
</ul>
</div>
<%= link_to "Create a Group", new_group_path %>
<%= link_to "View All Groups", groups_path %>
<%= link_to "Add a task", new_group_group_task_path(@group) %>