config/routes.rb
Rails.application.routes.draw do

  # get '/groups/new', to: 'groups#new', as: 'new_group'
  # get '/groups/:id', to: 'groups#show', as: 'group'
  
  root to: 'users#index'

  get '/auth/github/callback' => 'sessions#create'

  get '/signup', to: 'users#new', as: 'users'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  # post '/users/:user_id/groups', to: 'groups#create', as: 'user_groups'

  get '/users/most_tasks', to: 'users#most_tasks', as: 'most_tasks'


  # get '/groups/:id/group_tasks', to: 'group_tasks#new', as: 'new_group_group_task'
  # post '/groups/:id/group_tasks', to: 'group_tasks#create', as: 'group_tasks'
  # patch '/group_tasks/:id/edit', to: 'group_tasks#update', as: 'group_group_task'
  # get '/groups/:id/new', to: 'group_tasks#new', as: 'new_group_task'
  # patch '/groups/:group_id/goal', to: 'goals#create', as: 'group_goal'
  # #group goals
  # get '/groups/:id/goal', to: 'goals#new', as: 'group_goals'
  # post '/goals', to: 'goals#create'
  # get '/groups/:id/goal/:id/edit', to: 'goals#edit', as: 'edit_group_goal'
  # patch 'groups/:id/goals/:id', to: 'goals#update'

  # #user goals
  # get '/users/:id/goal', to: 'goals#new', as: 'user_goals'
  # post '/users/:id/goal', to: 'goals#create'
  # get '/users/:user_id/goal/:id/edit', to: 'goals#edit', as: 'edit_user_goal'
  patch '/goals/:id', to: 'goals#update'
  post '/goals', to: 'goals#create'

  # post '/users/:id/tasks', to: 'tasks#create'
  # delete '/task/:id', to: 'tasks#destroy', as: 'task'
# patch '/users/:user_id/tasks/:id', to: 'tasks#update'
# get '/users/:user_id/tasks/:id/edit', to: 'tasks#edit', as: 'edit_user_tasks'

  # delete 'groups/:group_id/task/:id', to: 'group_tasks#destroy', as: 'group_task'

  #Comments
  get '/users/:user_id/tasks/:id/comment', to: 'tasks#edit', as: 'comment_user_tasks'
  patch '/users/:user_id/tasks/:id/comment', to: 'tasks#update', as: 'update_comment_user_tasks'
  
  
  get '/groups/:group_id/tasks/:id/comment', to: 'group_tasks#edit', as: 'comment_group_task'
  patch '/groups/:group_id/tasks/:id/comment', to: 'group_tasks#update', as: 'update_comment_group_task'

  
 
  
  

  
  get '/users/:user_id/groups/:id/edit', to: 'groups#edit', as: 'edit_user_group'
  get '/users/:user_id/tasks/:id/goal/:status', to: 'tasks#edit', as: 'goal_user_task'
  get 'groups/:group_id/tasks/:id/:complete', to: 'group_tasks#edit', as: 'complete_group_task'
  get 'users/:user_id/tasks/:id/:complete', to: 'tasks#edit', as: 'complete_user_task'
  

  resources :users, only: [:show, :edit, :update] do
    # resources :tasks, only: [:new, :create, :edit, :update]
    resources :tasks, only: [:new, :create, :edit, :update, :destroy]
    resources :goals, only: [:new, :create, :show, :edit, :update]
  end

  resources :groups do
    resources :group_tasks, only: [:new, :create, :update, :destroy]
    resources :goals, only: [:new, :create, :edit, :update]
  end
  

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :category_users
  
  has_many :goals
  has_many :tasks
  has_many :categories, through: :tasks
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :group_tasks, through: :groups
  validates_presence_of :username
  validates :username, uniqueness: :true
  accepts_nested_attributes_for :tasks


  scope :most_tasks, -> {left_joins(:tasks).group(:id).order('count(tasks.user_id) desc') }
  scope :most_unfinished_tasks, -> { most_tasks.where('complete = false').limit(1) }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index, :new, :create]

    def index
        render :home
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def most_tasks
    end

    def show
        # binding.pry
        if @user = User.find_by_id(params[:id])
        else
            flash[:message] = "Must be signed in as user to view user's page!"
            redirect_to :root
        end
        
        if !current_user.groups.nil?
            @group = Group.new
        end
    end

    def edit
        if params[:id] && @user = User.find_by_id(params[:id])
        else
            flash[:message] = "Must be signed in as user to edit user's page!"
            redirect_to :root
        end
    end

    def update
            user = User.find_by_id(params[:id])
            redirect_to groups_path if !user == current_user
            group = Group.find(params[:user][:group][:id])
            if params[:commit] == "Leave Group"
                user.groups.delete(group)
                redirect_to user_path(user)
            else
                    user.groups << group
                    redirect_to user_path(user)
            end
    end

    private

    def user_params
        params.require(:user).permit(                            
          :username,
          :password,
          :email,
          group_ids:[],
          group: [
              :name
          ],
          tasks_attributes: [ 
          :comment,
          :complete
          ]
        )
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def group_names=(name)
    group = Group.find_or_create_by(name: group_name)
    if !self.group.include?(group)
      self.groups << group
    end
end

def group_names(user)
  user.groups
end
end

app/views/users/edit.html.erb
<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user) do |f| %>
<%= f.fields_for :group do |b|%>
<%= b.collection_select :id, Group.all, :id, :name %>
<% end %>
<%= f.submit "Join Group"%>
<% end %>

<%= form_for(@user) do |f| %>
<%= f.fields_for :group do |b|%>
<%= b.collection_select :id, @user.groups, :id, :name %>
<% end %>
<%= f.submit "Leave Group"%>
<% end %>

app/views/users/home.html.erb
<% if !logged_in? %>
  Welcome! Please sign up or log in.
  <%= link_to('Log in with Github!', '/auth/github') %>
<% else %>
  Welcome <%= current_user.username %>!
  <% if current_user.email %>
  email: <%= current_user.email %>
<% end %>
<% end %>

app/views/users/most_tasks.html.erb
<h2>User with the most tasks to complete:</h2>
<h3><%= User.most_tasks.first.username %></h3>

app/views/users/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @user} %>

<h1>Sign Up</h1>
  <% if !@user.errors.empty? %>
  <%= @user.errors.each do |error| %>
  <%=   error %><br>
  <%  end %>
  <%  end %>

<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  </br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  </br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %>!</h1>
<% if @user.tasks.empty? %>
<p>You don't have any Tasks.</p>
<% end %>
<br>
<p>
<h3><b>Your Groups:</b></h3>
<ol>
<% @user.groups.uniq.each do |group| %>
     <li><%= link_to group.name, group_path(group) %> - Goal: 
     <% if group.goal %>
     <%= group.goal.name %></li>
     <% end %>
<% end %>
</ol>
<hr>
<p>
<h3><b>Your Individual Tasks:</b></h3>
<% @user.categories.uniq.each do |category| %>

     <h2>Category: <%= category.name %></h2><br>
     <% category.tasks.each do |task| %>
     <% if @user.tasks.include?(task)%>

          <% com = task.comment.nil? ? "Add Comment" : "Update Comment" %>
               <% if task.complete == true %>
                    <del><p><em><li><%= task.name  %></li></em></del><em> (Task Completed!)</em>
                    <% if task.goal.nil? %>
                         <h3>If this task aims at achieving a goal, please select the goal for the task: </h3>
                         <%= form_with model: task, method: :patch, url: user_task_path(@user, task) do |f| %>
                         <%= f.collection_select :goal, Goal.all, :name, :name %>
                         <%= f.submit %>
                         <% end %>
                    <% else %>
                         <i>Goal= </i><b><%= task.goal %></b>
                    <% end %><br>
               <% if !task.comment.nil? %>
                    <b>Comment:</b> 
               <% end %>
               <em><%= task.comment %></em></p>
               <%= link_to com, comment_user_tasks_path(@user, task) %>
               <%= link_to "Remove Goal From Task", goal_user_task_path(@user, task, "nil") %>
                <%= link_to "Delete Task", user_task_path(@user, task), method: :delete %>
               <% else %>
               <p><em><li><%= task.name  %></li></em>
                <% if task.goal.nil? %>
                    <h3>If this task aims at achieving a goal, please select the goal for the task: </h3>
                    <%= form_with model: task, method: :patch, url: user_task_path(@user, task) do |f| %> 
                    <%= f.label :goal, "Select or Create A Goal"  %>
  <em><%= f.text_field :goal, list: "goals_autocomplete" %></em>
   <datalist id="goals_autocomplete">
    <% Goal.all.each do |goal| %>
      <option value=<%= goal.name %>>
      <% end %>
   </datalist>
   <%= f.submit %>
                    <% end %>
               <% else %>
               <i>Goal= </i><b><%= task.goal %></b>
               <% end %><br>
               <% if !task.comment.nil? %>
                    <b>Comment:</b> 
               <% end %>
                    <em><%= task.comment %></em></p>          
                    <%= link_to com, comment_user_tasks_path(@user, task) %>
                    <%= link_to "Completed?", complete_user_task_path(@user, task, "true") %>
                    <%= link_to "Change Goal", goal_user_task_path(@user, task, "nil")%>
                    <%= link_to "Delete Task", user_task_path(@user, task), method: :delete %>
               <% end%>
                <br>
          <% end%>
         
     <% end %>
  <br>
  <hr>
</ol>
<% end %>
</div>


<%= link_to "Join or Leave a Group", edit_user_path(@user) %>
<%= link_to "Create a Group", new_group_path %>
<%= link_to "Add a task", new_user_task_path(@user) %>