config/routes.rb
Rails.application.routes.draw do

  # get '/groups/new', to: 'groups#new', as: 'new_group'
  # get '/groups/:id', to: 'groups#show', as: 'group'
  
  root to: 'users#index'

  get '/auth/github/callback' => 'sessions#create'

  get '/signup', to: 'users#new', as: 'users'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  # post '/users/:user_id/groups', to: 'groups#create', as: 'user_groups'

  get '/users/most_tasks', to: 'users#most_tasks', as: 'most_tasks'


  # get '/groups/:id/group_tasks', to: 'group_tasks#new', as: 'new_group_group_task'
  # post '/groups/:id/group_tasks', to: 'group_tasks#create', as: 'group_tasks'
  # patch '/group_tasks/:id/edit', to: 'group_tasks#update', as: 'group_group_task'
  # get '/groups/:id/new', to: 'group_tasks#new', as: 'new_group_task'
  # patch '/groups/:group_id/goal', to: 'goals#create', as: 'group_goal'
  # #group goals
  # get '/groups/:id/goal', to: 'goals#new', as: 'group_goals'
  # post '/goals', to: 'goals#create'
  # get '/groups/:id/goal/:id/edit', to: 'goals#edit', as: 'edit_group_goal'
  # patch 'groups/:id/goals/:id', to: 'goals#update'

  # #user goals
  # get '/users/:id/goal', to: 'goals#new', as: 'user_goals'
  # post '/users/:id/goal', to: 'goals#create'
  # get '/users/:user_id/goal/:id/edit', to: 'goals#edit', as: 'edit_user_goal'
  patch '/goals/:id', to: 'goals#update'
  post '/goals', to: 'goals#create'

  # post '/users/:id/tasks', to: 'tasks#create'
  # delete '/task/:id', to: 'tasks#destroy', as: 'task'
# patch '/users/:user_id/tasks/:id', to: 'tasks#update'
# get '/users/:user_id/tasks/:id/edit', to: 'tasks#edit', as: 'edit_user_tasks'

  # delete 'groups/:group_id/task/:id', to: 'group_tasks#destroy', as: 'group_task'

  #Comments
  get '/users/:user_id/tasks/:id/comment', to: 'tasks#edit', as: 'comment_user_tasks'
  patch '/users/:user_id/tasks/:id/comment', to: 'tasks#update', as: 'update_comment_user_tasks'
  
  
  get '/groups/:group_id/tasks/:id/comment', to: 'group_tasks#edit', as: 'comment_group_task'
  patch '/groups/:group_id/tasks/:id/comment', to: 'group_tasks#update', as: 'update_comment_group_task'

  
 
  
  

  
  get '/users/:user_id/groups/:id/edit', to: 'groups#edit', as: 'edit_user_group'
  get '/users/:user_id/tasks/:id/goal/:status', to: 'tasks#edit', as: 'goal_user_task'
  get 'groups/:group_id/tasks/:id/:complete', to: 'group_tasks#edit', as: 'complete_group_task'
  get 'users/:user_id/tasks/:id/:complete', to: 'tasks#edit', as: 'complete_user_task'
  

  resources :users, only: [:show, :edit, :update] do
    # resources :tasks, only: [:new, :create, :edit, :update]
    resources :tasks, only: [:new, :create, :edit, :update, :destroy]
    resources :goals, only: [:new, :create, :show, :edit, :update]
  end

  resources :groups do
    resources :group_tasks, only: [:new, :create, :update, :destroy]
    resources :goals, only: [:new, :create, :edit, :update]
  end
  

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def category_name=(name)
    self.category = Category.find_or_create_by(:name => name)
    
    # self.category.update(name: name)
  end

  def category_name
    self.category ? self.category.name : nil
  end

  def group_name=(name)
    self.group = Group.find_or_create_by(:name => name)
    # self.group.update(name: name)
  end

  def group_name
    self.group ? self.group.name : nil
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
  has_many :users, through: :tasks
  has_many :group_tasks
  has_many :groups, through: :group_tasks 
  has_many :category_users
  validates :name, uniqueness: true
  validates_presence_of :name
end

app/models/category_user.rb
class CategoryUser < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user, optional: true
  belongs_to :group, optional: true
  # validates :name, uniqueness: true
  validate :user_goal_name_unique

  def user_goal_name_unique
    if self.group_id == nil
      user = User.find(user_id)
      if user.goals.name.include?(self.name)
        errors.add(:goal_id, "That name has already been taken")
      end
    end
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_tasks
  has_many :group_users
  has_many :categories, through: :group_tasks
  has_many :users, through: :group_users
  has_many :tasks
  has_one :goal
  validates_presence_of :name
  validates_uniqueness_of :name
  
  
  
  # def my_link_to(text, href)
  #   if !group_member
  #   flash[:message] = "Must be a part of group to view page" if self.users.include?(current_user)
  #   redirect_to request.referrer
  #   else 
  #     "<a href='#{href}'>#{text}</a>".html_safe
  #   end
  # end



  def group_member?
    self.users.include?(@user)
  end

  
end

app/models/group_task.rb
class GroupTask < ApplicationRecord
  belongs_to :goal, optional: true
  belongs_to :category
  belongs_to :group
  has_many :users, through: :group
  validates :name, presence: true
  validate :group_task_name_not_duplicate
  

  def group_task_name_not_duplicate
    task = GroupTask.find_by(name: name, group_id: group_id)
      if !!task && task != self
      errors.add(self.name, "is already a task.")
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user
  validates_presence_of :name
  validate :task_name_not_duplicate
  scope :alpha, -> { order(:name) }

  def task_name_not_duplicate
    task = Task.find_by(name: name, user_id: user_id)
      if !!task && task != self
      errors.add(self.name, "is already a task.")
    end
  end
end

app/models/task_user.rb
class TaskUser < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :category_users
  
  has_many :goals
  has_many :tasks
  has_many :categories, through: :tasks
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :group_tasks, through: :groups
  validates_presence_of :username
  validates :username, uniqueness: :true
  accepts_nested_attributes_for :tasks


  scope :most_tasks, -> {left_joins(:tasks).group(:id).order('count(tasks.user_id) desc') }
  scope :most_unfinished_tasks, -> { most_tasks.where('complete = false').limit(1) }
  
end

app/models/user_group.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/task_users_helper.rb
module TaskUsersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/usergroups_helper.rb
module UsergroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def group_names=(name)
    group = Group.find_or_create_by(name: group_name)
    if !self.group.include?(group)
      self.groups << group
    end
end

def group_names(user)
  user.groups
end
end

app/views/layouts/_errors.html.erb

<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <% if !current_user %>
          <a class="navbar-brand" href="<%= signup_path %>"/>Sign Up</a>
          <%= link_to "Log in", login_path, class:"navbar-brand" %>
        <% end %>

        <% if logged_in? %>
      
          <%= link_to "#{current_user.username}'s user profile", user_path(current_user), class:"navbar-brand"%>
          <%= link_to "View All Groups", groups_path %>
          <%= link_to "Log Out", logout_path, class:"navbar-brand",method:'delete' %>
        <% end %>
        <%= link_to 'User with most tasks yet to complete', most_tasks_path %>
        <%= link_to 'Back', :back unless !request.original_url.include?("users" || "groups") %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
    <div><% if flash[:message] %>
      <strong><%= flash[:message] %></strong>
      <% end %>
    <div><% if !@error.nil?  %>
      <strong><%= @error %></strong>
      <% end %>
      </div>
      <%= yield %>
      <% @error = nil %>
    </div>
  </body>
</html>